# Generated by Django 3.2 on 2022-09-02 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c0890d43-a2b6-4d98-b5bd-9b109257edc0'), primary_key=True, serialize=False),
        ),
    ]
