# Generated by Django 3.2 on 2022-07-13 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_baseuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3a2eda7e-fa5f-4e54-b289-2cf2b875961d'), primary_key=True, serialize=False),
        ),
    ]
